name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 'lts/*'
          args: --frozen-lockfile
      - name: Run tests
        run: pnpm test
